### PR TITLE
Improve emojiExists function

### PR DESCRIPTION
**Pull request by 9inpachi**
Hi,

Was trying to contribute a bit and found this code. :D
I found that ecmascript works so here's a better version of the function.

I'll be on the lookout for any issues if I get the time. :)

### CODE REVIEW

**Comment by supertiger1234** [comment]
👌

**Comment by 9inpachi** [comment]
Bro. There was an issue. I returned the shortcode instead of the emoji.
I just pushed but was too late I guess. :D

**Comment by supertiger1234** [comment]
oh xD what now?

**Comment by 9inpachi** [comment]
I can create another PR, or you can change the code manually.
I guess the latter will be faster xD

**Comment by supertiger1234** [comment]
ill do it :D

**Pull request merged**
